description = "Alpine 3.x tiny image with only Java buildpacks included. To use, specify buildpacks at build time."

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/java-native-image:14.11.0"
  version = "14.11.0"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/java:22.4.0"
  version = "22.4.0"

[lifecycle]
  version = "0.21.18"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/java-native-image"
    version = "14.11.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/java"
    version = "22.4.0"

[stack]
  build-image = "docker.io/patbaumgartner/buildpack-base-build:alpine"
  id = "com.patbaumgartner.stacks.alpine"
  run-image = "docker.io/patbaumgartner/buildpack-base-run:alpine"
  run-image-mirrors = []

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"