description = "Ubuntu 24.04 Noble Numbat tiny image with only Java buildpacks included. To use, specify buildpacks at build time."

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/java-native-image:11.10.0"
  version = "11.10.0"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/java:18.6.0"
  version = "18.6.0"

[lifecycle]
  version = "0.20.8"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/java-native-image"
    version = "11.10.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/java"
    version = "18.6.0"

[stack]
  build-image = "docker.io/patbaumgartner/buildpack-base-build:noble"
  id = "com.patbaumgartner.stacks.noble"
  run-image = "docker.io/patbaumgartner/buildpack-base-run:noble"
  run-image-mirrors = []

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"